migrations/20220219033006-create-activity.js
models/activity.js

COMO usuario administrador
QUIERO gestionar las Actividades de la ONG
PARA poder informarlas en el sistema
Las Actividades de la ONG podrán ser gestionadas desde el backoffice. Nombre de tabla: activities. Contendrá los campos name, image, content, deletedAt (utilizada para soft delete)

Activity model and migration created

---

.eslintrc.json
app.js
controllers/categories.js
controllers/index.js
helpers/validateInDB.js
middlewares/categories.js
middlewares/index.js
package.json
routes/categories.js
routes/index.js

Add a news categories with administrator privileges.

OT141-43 | Create category 

---

.eslintrc.json
app.js
controllers/categories.js
controllers/index.js
helpers/validateInDB.js
middlewares/categories.js
middlewares/index.js
package.json
routes/categories.js
routes/index.js

Feature for get all categories

Ot141-41 | List categories

---

.gitignore
app.js
documentation/authentication.yml
documentation/config.swagger.js
package-lock.json
package.json

- COMO desarrollador
QUIERO disponer de una documentación de los endpoints de autenticación
PARA tener referencias de su funcionamiento
- Criterios de aceptación:
Se deberán documentar los diferentes endpoints 
especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

Ot141 94 agregar documentación a autenti

---

controllers/category.js
routes/categories.js

COMO usuario administrador
QUIERO modificar una categoría existente
PARA mantener la información actualizada
PUT /categories/:id - Deberá validar que la categoría existe y actualizarla, caso contrario devolver un error

0T141-44-endpoint-actualizacion-categoriass

---

migrations/20200921211634-create-user.js
models/user.js

- Campos:id: INTEGER NOT NULL AUTO_INCREMENT
- firstName: VARCHAR NOT NULL
- lastName: VARCHAR NOT NULL
- email: VARCHAR UNIQUE NOT NULL
- password: VARCHAR NOT NULL
- photo: VARCHAR NULLABLE
- roleId: Clave foranea hacia ID de Role
- timestamps y softDeletes

Add Ticket 17 | migration and model User (details)

---

helpers/uploadAWS-S3.js
package-lock.json
package.json

- COMO usuario administrador
QUIERO subir imágenes en el sistema
PARA mejorar la comunicación
- Criterios de aceptación:
Se deberá vincular el servicio para manejo de archivos Amazon S3, a través de su SDK para Node.js. El mismo se utilizará posteriormente para campos de diferentes entidades, como la foto de perfil del usuario, logo de ONG, imágenes del blog y demás, por lo que debe crearse un servicio reutilizable para el manejo de archivos.

Ot141 39 setup amazon s3 sdk

---

app.js
documentation/activities.yml

Descripción
COMO desarrollador
QUIERO disponer de una documentación de los endpoints de la API
PARA tener referencias del funcionamiento del sistema
Se deberá implementar la librería Swagger para documentar los diferentes endpoints del proyecto. Al ingresar al endpoint /api/docs, se deberá mostrar el layout. Adicionalmente, agregar la posibilidad para implementar los diferentes schemas en base a los Comentarios de métodos de cada controlador.

OT141-89- add activities documentation

---

controllers/auth.js
routes/auth.js

COMO usuario
QUIERO obtener mis datos
PARA tener conocimiento de la información que almaceno en el sistema
/GET auth/me - Deben devolver los datos del usuario autenticado, obteniendo al mismo desde el token enviado en el header Authorization

0T141-37-endpoint-dato-usuario-autenticado

---

app.js
controllers/comment.controller.js
routes/comments.js

- COMO usuario 
QUIERO visualizar los Comentarios de un post
PARA obtener la información organizada
- Criterios de aceptación:
GET /posts/:id/comments - Devolverá todos los Comentarios pertenecientes a un post

Ticket 84 - Completed

---

controllers/comment.controller.js
middlewares/comment.validations.js
routes/comments.js

COMO usuario
QUIERO dar de alta nuevos Comentarios
PARA agregarlos a un post existente
POST /comments - Deberá validar que se envíe el campo post_id, user_id y body

Feature/ot141 81 endpoint creación comentarios

---

controllers/category.js
helpers/paginated.js
migrations/20220310124215-create-category.js
models/category.js

Mejore la función de paginación para optimizar la cantidad de información que antes se traía de la base de datos.

Ticket 85 - PAGINATION CATEGORIES REPAIRED

---

app.js
controllers/index.js
controllers/members.js
middlewares/index.js
middlewares/members.js
migrations/20220315001958-create-member.js
models/member.js
routes/members.js

COMO usuario
QUIERO crear un miembro
PARA actualizar la información de la web.
POST /members - Deberá validar que se envíe el campo name, y el mismo sea un string

OT141-74 | Endpoint create members

---

documentation/members.yml

COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Miembros
PARA tener referencias de su funcionamiento
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

0T141-92-agregar-documentacion-a-miembros

---

documentation/category.yml

documentacion de categorias probada funcionando

FIXED - Ot141 90 agregar documentacion a categoria

---

app.js
controllers/new.controller.js
routes/news.js

COMO usuario administrador
QUIERO ver los detalles de una novedad
PARA poder informar actualizaciones del contenido
GET a /news/:id . Mostrará todos los campos de una entry en base al id enviado por parámetro.

0T141-46-add endpoint GET:id New

---

controllers/new.controller.js
routes/news.js

COMO usuario administrador
QUIERO agregar una novedad en el sistema
PARA poder informar las Novedades de la ONG
POST /news - Deberá validar la existencia de los campos enviados, para almacenar el registro en la tabla news. Antes de almacenarla, deberá asignarle la columna type con el valor "news".

0T141-47-endpoint-creacion-novedades

---

documentation/testimonials.yml

COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Testimonios
PARA tener referencias de su funcionamiento
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

OT141-93 | Create testimonials documentation

---

app.js
controllers/activity.js
controllers/auth.js
controllers/category.js
controllers/index.js
controllers/member.js
controllers/testimony.js
controllers/user.js
models/user.js
package-lock.json
package.json

- COMO usuario administrador
QUIERO subir imágenes en el sistema
PARA mejorar la comunicación
- Criterios de aceptación:
El mismo se deberá integrar con los métodos existentes que manejen imágenes. 
Se encargará de almacenar una imagen en Amazon y devolver la ruta absoluta hacia el bucket

Ot141 40 servicio reutilizable para subi

---

migrations/20220318013156-create-new.js
models/new.js
seeders/20220318021938-create-categories.js
seeders/20220318022552-create-news.js

Tuve que hacer este ticket para poder hacer el del get y post .
Campos:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
content: TEXT NOT NULL
image: VARCHAR NOT NULL
categoryId: Clave foranea hacia ID de Categories
timestamps y softDeletes
Se agrego seeders para Categories y News

0T141-19 crear modelo migracion news
